README.md
package.json

Andre's suggested changes to `package.json`

---

src/markets.js

Actually add documentation for createMarket

---

src/lmsr.js
src/utils.js
test/test_gnosis.js

@andre-meyer
Some new functionality for 0.3.0

Add marginal price func

---

src/lmsr.js
test/test_gnosis.js

Fix rounding

---

src/events.js
src/index.js
src/lmsr.js
src/markets.js
src/oracles.js
src/utils.js
test/test_gnosis.js

Not a complete set of validators yet...

Validate inputs and refactor based on ABI

---

package.json
src/utils.js
test/test_gnosis.js

Arg immutability

---

src/markets.js

Approve the correct amount for buying

---

README.md
package-lock.json
package.json
src/events.js
src/index.js
src/markets.js
src/utils.js
test/test_gnosis.js
webpack.config.js

Gnosis now has a gas estimator:
```javascript
// using the estimateGas RPC
await gnosis.createCentralizedOracle.estimateGas(ipfsHash, { using: 'rpc' }))
// using stats derived from gnosis-contracts
await gnosis.createCentralizedOracle.estimateGas({ using: 'stats' }))
```

Gas estimator

---

package-lock.json
package.json
src/index.js

Depends on https://github.com/gnosis/gnosis-contracts/pull/58

Add ref to human-friendly contract

---

package-lock.json
package.json
src/markets.js

Depends on https://github.com/trufflesuite/truffle-contract/pull/73 because of https://github.com/trufflesuite/truffle-contract/issues/42

Synchronize approve and buy transaction hashes

---

src/utils.js
test/test_gnosis.js

See https://gnosisltd.atlassian.net/browse/PM-340

Decimals now admit exponentless representation

---

src/events.js
src/index.js
src/markets.js
src/utils.js
test/test_gnosis.js

Just add the `logger: "console"` option to `GNOSIS_OPTIONS` and you can see more logs.

More error reporting

---

src/markets.js
src/utils.js
test/test_gnosis.js

Basically creating markets on the interface should work after this

Account for serialization behavior differences across environments

---

.eslintignore
.gitignore
.npmignore
package-lock.json
package.json
src/index.js
test/multidep.json
test/test_events.js
test/test_gnosis.js
test/test_utils.js

I think this covers the main use cases.

Add web3 1.0 support

---

package-lock.json
package.json

Setting up for future changes to the core contracts: https://gnosisltd.atlassian.net/browse/PM-527

Specify core contracts as a peer dep instead of regular dep

---

docs/source/installation.md

Thanks Roger Ganga on the gnosis/GnosisX Gitter channel for the heads up on Powershell

Account for Powershell

---

.travis.yml
src/lmsr.js
test/test_markets.js

Check it out :o
https://gnosisltd.atlassian.net/browse/PM-596

Local LMSR calcs now report Non-NaN values for unfunded markets

---

docs/source/api-overview.md
docs/source/installation.md

Made straggling rename edits

---

package-lock.json
package.json
test/multidep.json

web3 1.0.0-beta does not work with this code yet.
See #126

Use a codebase-compatible version of web3

---

src/index.js
src/markets.js
test/test_gnosis.js
test/test_markets.js

This also addresses a nit from #130

Fix contract names
